artifacts_root : artifacts

data_ingestion  : 
  root_dir      : artifacts/datas
  image_path    : artifacts/datas/image
  mask_path     : artifacts/datas/mask
  csv_file_path : artifacts/datas/images_masks


